@host = http://localhost:8080
@accountId = 5b19c8b6-0cc4-4c72-a989-0c2ee15fa975

### Consulta o saldo atual
GET {{host}}/balances/{{accountId}}
Accept: application/json

### Conta inexistente
GET {{host}}/balances/00000000-0000-0000-0000-000000000000
Accept: application/json
